---
matrix:
  include:

    - language: node_js
      node_js:
        - "10"
      dist: trusty
      sudo: required
      script:
        - cd frontend
        - npm install -g @angular/cli
        - ng build --prod --base-href https://github.com/TJZhou/pigeon-calendar-springboot/tree/master/frontend/

    - language: java
      dist: trusty
      script:
        - cd backend
        - mvn package